parameters:
    gsynchro.importPath: '%env(resolve:GRIIVSYNCHRO_IMPORT_PATH)%'
    gsynchro.importPathFixtures: '%env(resolve:GRIIVSYNCHRO_IMPORT_PATH_FIXTURES)%'
    gsynchro.importBackup: '%env(resolve:GRIIVSYNCHRO_IMPORT_BACKUP)%'
    gsynchro.exportPath: '%env(resolve:GRIIVSYNCHRO_EXPORT_PATH)%'
    gsynchro.exportBackup: '%env(resolve:GRIIVSYNCHRO_EXPORT_BACKUP)%'
    gsynchro.logsPath: '%env(resolve:GRIIVSYNCHRO_LOGS_PATH)%'
    gsynchro.batchSynchro: '%env(resolve:GRIIVSYNCHRO_BATCH_SYNCHRO)%'
    gsynchro.lockPath: '%env(resolve:GRIIVSYNCHRO_LOCK_PATH)%'
    gsynchro.enableEmailNotification: '%env(resolve:GRIIVSYNCHRO_ENABLE_EMAIL_NOTIFICATION)%'
    gsynchro.enableKchatNotification: '%env(resolve:GRIIVSYNCHRO_ENABLE_KCHAT_NOTIFICATION)%'

services:
    _defaults:
        public: true

    #Commands
    griiv.synchro.console.add.export.command:
        class: Griiv\SynchroEngine\Command\AddExportCommand
        tags: [ console.command ]

    griiv.synchro.console.add.import.command:
        class: Griiv\SynchroEngine\Command\AddImportCommand
        tags: [ console.command ]

    griiv.synchro.console.add.sequence.command:
        class: Griiv\SynchroEngine\Command\AddSequenceCommand
        tags: [ console.command ]

    griiv.synchro.console.create.ftp.folders.command:
        class: Griiv\SynchroEngine\Command\CreateFtpFoldersCommand
        tags: [ console.command ]

    griiv.synchro.console.execute.command:
        class: Griiv\SynchroEngine\Command\ExecuteCommand
        arguments:
            - !tagged_iterator 'gsynchro.synchro'
        tags: [ console.command ]

    griiv.synchro.console.log.rotate.command:
        class: Griiv\SynchroEngine\Command\LogRotateCommand
        tags: [ console.command ]

    #services

    griiv.synchro.helpers.synchrohelper:
        class: 'Griiv\SynchroEngine\Synchro\Helpers\SynchroHelper'
        arguments:
            - '@service_container'