<?php

namespace Griiv\${moduleName}\Synchro\Export;

use Griiv\SynchroEngine\Synchro\ExportBase;

class ${exportName}Export extends ExportBase
{

    protected function initDataTargets()
    {
        // TODO: Implement initDataTargets() method.
    }

    protected function initTargetItemDefinition()
    {
        // TODO: Implement initTargetItemDefinition() method.
    }

    protected function initDataSources()
    {
        // TODO: Implement initDataSources() method.
    }

    protected function initItemDefinition()
    {
        // TODO: Implement initItemDefinition() method.
    }

    protected function processRow($dataArray)
    {
        return parent::processRow($dataArray); // TODO: Change the autogenerated stub
    }
}
